name: Daily Reminder

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "*/15 * * * *" # every hr
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Code checkout
      - name: Checkout
        uses: actions/checkout@v4

      # JDK Setup
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          # Available options https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions
          distribution: 'corretto'
          java-version: '17'
          # cache: 'gradle'

      - name: Get current time in IST
        id: get_ist_time
        run: |
          IST_TIME=$(TZ="Asia/Kolkata" date +"%Y-%m-%d %H:%M:%S")
          echo "IST_TIME=$IST_TIME" >> $GITHUB_ENV

      - name: Use IST time in next step
        run: |
          echo "The current time in IST is $IST_TIME"

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true --file pom.xml --no-transfer-progress

      - name: Send Notifications
        env:
          GAYYA_ENV_MODE: "DEV"
          GAYYA_DAILY_REMINDER_CHANNEL_ID: ${{ vars.GAYYA_DAILY_REMINDER_CHANNEL_ID }}
          GAYYA_FIREBASE_DATABASE_URL: ${{ vars.GAYYA_FIREBASE_DATABASE_URL }}
          GAYYA_FIREBASE_SERVICE_ACCOUNT_JSON_FILE: ${{ secrets.GAYYA_FIREBASE_SERVICE_ACCOUNT_JSON_FILE }}
          GAYYA_IST_TIME: ${{ env.IST_TIME }}  # Pass IST_TIME to the Spring Boot app
        run: java -jar target/gayya-notification-scheduler.jar --logging.level.root=DEBUG


